version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/opt/app/config
      - ./data:/opt/app/data
    # image: esoadamo/cloudflare-oicd-proxy
    restart: always
    # env_file:
    #   - .env
    ports:
      - ${PORT}:${PORT}
